version: "3.9"

services:

  db:
    image: postgres
    container_name: adminer
    restart: always
    ports: 
    - 5432:5432
    environment:
      - POSTGRES_USER=dbuser_cliente
      - POSTGRES_PASSWORD=rootadmin123456
      - POSTGRES_DB=db_client
    volumes:
    - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
 